# Generated by Django 5.2.7 on 2025-10-16 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especialidad', models.CharField(default='General', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('diagnostico', models.TextField(blank=True, default='Sin diagnóstico')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='patients.doctor')),
            ],
        ),
    ]
